export const ROUTER = {
  USER: {
    HOME: "home",
    PROFILE: "profile",
    PRODUCT: "product",
    LOGIN: "login",
    TICKET_SEARCH: "ticket-search",
    INTRODUCE: "introduce",
    CONTACT: "contact",
    SCHEDULE: "schedule",
    BOOK_TICKET: "book-ticket",
    TICKET_HISTORY: "ticket-history",
    PAYMENT: "payment",
    ACCOUNT_INFO: "account-info",
    ADDRESS: "address",
    RESET_PASSWORD: "reset-password",
    GUIDE: "guide",
    NEWS: "news",
  },
  ADMIN: {
    HOMEADMIN: "admin",
    ADDTRIP: "/admin/add-trip",
    MANAGETRIPS: "/admin/manage-trips",
    MANAGEUSERS: "/admin/manage-users",
    STATISTICS: "/admin/statistics",
  },
};
